### ISSUE TITLE
Is there an option to define color for the labels of the vectors?

### ISSUE THREAD

**Issue by gaurakshay** [fawda123/ggord#10]
As the title says, I couldn't find an option to define the label for the vectors. Maybe I missed it. Could you please advise if there is a way to define colors for labels?

I can change the color of the vectors using `veccol` but am unable to change the color of the labels as well.

**Comment by fawda123** [comment]
Hi there, I just added the `labcol` argument to change the color of text labels.  3ab92acdf1dffa262690d1d993849e84f6f7a27b

```r
library(ggord)

ord <- prcomp(iris[, 1:4])

p <- ggord(ord, iris$Species, labcol = 'purple')
p
```
