### ISSUE TITLE
Reducing number of vectors

### ISSUE THREAD

**Issue by p-neves** [fawda123/ggord#14]
Hi:

Is it possible to reduce the number of plotted vectors on an ordination plot? I want to make an nmds plot and my vectors (species) are too many, obscuring the graph. Is there a way to define which vectors to plot, e.g. by setting a threshold on the abundance?

**Comment by fawda123** [comment]
Here's a manual solution removing Sepal.Length using NA for vector type and label color:
```r
ggord(ord, iris$Species, vectyp =  c(NA, 'solid', 'solid', 'solid'), labcol= c(NA, 'black', 'black', 'black'))
```
![image](https://user-images.githubusercontent.com/3086881/52921380-3e827e00-32cb-11e9-901b-22cb03ffd692.png)

I think a bigger question though is whether or not its misleading to show some vectors and not others.  If it's an issue of data overload, I would consider refitting the model with less species (or maybe group by genus?). Perhaps removing those with very low abundance would be a good start as rare species can really skew some multivariate methods.
