### ISSUE TITLE
Word 'italic' showing up in rda plots

### ISSUE THREAD

**Issue by jeduchamp** [fawda123/ggord#16]
# Issues

Any issues or feature requests can be posted on the [issues](https://github.com/fawda123/ggord/issues) page. Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or send me a direct message.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
When running ggord on an rda from package vegan, the species names include the word 'italic'.  I edited the ggord.default function in my own script file to fix it, but I wanted to let you all know.  
I am using R version 4.0.
Below is my fix to ggord.default, but I expect there is a better way.  The ### indicate a line that I edited.
* My fix to ggord.default
```r{}
 # add species scores if addpts not null, for triplot
  if(!is.null(addpts)){

    addpts$lab <- paste0('', row.names(addpts), '') ###
    nms <- names(addpts)[1:2]
    names(addpts)[1:2] <- c('one', 'two')

    # pts as text labels if TRUE
    if(ptslab){
      p <- p +
        geom_text(data = addpts, aes_string(x = 'one', y = 'two', label = 'lab'),
          size = addsize, col = addcol, alpha = alpha, parse = parse, fontface=3) ###
    } else {
      p <- p +
        geom_point(data = addpts, aes_string(x = 'one', y = 'two'),
          size = addsize, col = addcol, alpha = alpha, shape = addpch)
    }
  }
```
---
* Example
```r
easypackages::libraries("ggplot2", "ggord", "vegan")

data(dune)
data(dune.env)
dune.Manure <- rda(dune ~ Manure, dune.env)

ggord(dune.Manure, ptslab = TRUE, ellipse = FALSE, hull=TRUE, poly=FALSE, repel=T, veclsz = 0.75)
```
![reprex-ggord rda italics issue](https://user-images.githubusercontent.com/65374478/81997411-a1250f80-961d-11ea-9a10-2d5e9b82439f.jpeg)

**Comment by fawda123** [comment]
Thanks for the reprex. It will work if you just set `parse = TRUE` in your plot call.  I've just changed this to the default fa8e1ebab27f45a5a73a10f12a80d0f6be160daf

**Comment by jeduchamp** [comment]
That’s great.  Thanks!

Joe Duchamp
Associate Professor
Department of Biology
Indiana University of Pennsylvania
________________________________
