### ISSUE TITLE
Request - GGord  repel = True AND maxoverlap / force

### ISSUE THREAD

**Issue by Galpac** [fawda123/ggord#17]
# Issues

Any issues or feature requests can be posted on the [issues](https://github.com/fawda123/ggord/issues) page. Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or send me a direct message.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

This is mostly a request, altough i wanted to ask first but i couldnt find anywhere to reach you (I even went to your wordpress); please, add a mail or something to contact in your home// send you the stackoverflow questions. (Or politely show them to mee cause it could be despise me searching for it that im blind as a bat)

Since i have not found how to vary the intra-arguments of ggrepel using ggord, just aplying true, i request thee.

When dealing with high correlated vectors from a ggord, like a pca, the ggrepel overlaps and i didnt manage to change the max_overlaps and/or the force so i could easily read the variables. I wish i had a reproducible example, but i cant find some free repositorys with the same issue as my data (wich i do not own to send/post)

All in all, thank you in advance and of course for this marvelous package :D.

```r
# insert reprex here
```

**Comment by fawda123** [comment]
@Galpac thanks for submitting the issue.  However, it's difficult to see exactly what you're asking without a reprex.  Is there another open dataset you could use to show the issue? Is it more an issue of being able to use some of the other native arguments in ggrepel?

**Comment by Galpac** [comment]
Im gonnna be bussy until the end of the week -probably even during
weekend-. Ill try to make a reprex with an open dataset but mostly it will
go as follow.
Generate 10 variables, correlated to each other.
Generate other 10 variables, correlated to each other but not with the
previosly 10.

Plot them with ggord. Since they are highly correlated, they plot in the
same way and their names and arrows gets all funky and cant read them.
Since ggord ggrepel has a limit to the number of names that can be plotted
next to each other, and we cant hcange the "force" parameter on ggrepel to
make them more separated therefore readable.

**Comment by fawda123** [comment]
Okay, I think I understand a bit more.  Would it be helpful if you could use the `force` argument directly in the `ggord` function?

**Comment by Galpac** [comment]
thruly helpfull. That one and the maximum overlap that i put in the first
message (the mail doesnt let me read it, and im currently working with
other data). I think in fact it woulndt just be usefull to me, but to
anyone using the function.

**Comment by fawda123** [comment]
@Galpac try it now, I just added those options as arguments in ggord.

**Comment by Galpac** [comment]
Maybe im doing something wrong here. Ill try to do the regex in the weekend.

[image: imagen.png]

**Comment by fawda123** [comment]
After you reinstall the package, does this work? The `max.overlap` argument is in there too, but it doesn't do anything for this example.

```
library(ggord)
library(patchwork)
set.seed(123)

ord <- prcomp(iris[, 1:4])

p1 <- ggord(ord, iris$Species, ext = 1, repel = T)

p2 <- ggord(ord, iris$Species, ext = 1, repel = T, force = 1000)

p1 + p2 + plot_layout(ncol = 1)
```
![image](https://user-images.githubusercontent.com/3086881/122558314-f1825400-d00b-11eb-9563-322b2fed6bb9.png)

**Comment by Galpac** [comment]
Sorry i have been hella bussy. IF i remember corretly it didnt work, but
since it was long ago i wil contactou further if i face again the issue.
Sorry and thank you :D

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
