### ISSUE TITLE
I can't install ggord

### ISSUE THREAD

**Issue by cmazier** [fawda123/ggord#18]
# Issues

Hello,

I would like to install ggord so I did:
library(devtools)
devtools::install_github('fawda123/ggord')
library(ggord)

But after I had this error:
Erreur : Failed to install 'ggord' from GitHub:
  create process 'C:/PROGRA~1/R/R-40~1.3/bin/x64/Rcmd.exe' (system error 267, Nom de répertoire non valide.
) @win/processx.c:1040 (processx_exec)

I reinstalled the last version of RTools and I had the last version of R. I also tried the commands:
devtools::install_github("r-lib/rlang")
OR
install.packages("rlang",type="win.binary") 

But I had the same error.

What can I do to install your package? I think it is because I have an accent on my computer username C:/ but I can't change it.

**Comment by fawda123** [comment]
Please use these installation instructions. 

```r
# Enable the r-universe repo
options(repos = c(
    fawda123 = 'https://fawda123.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'))

# Install ggord
install.packages('ggord')
```

**Comment by cmazier** [comment]
It works ! Thank you very much!
