### ISSUE TITLE
 arrow lines in CA plot

### ISSUE THREAD

**Issue by emsa999** [fawda123/ggord#4]
Thank you for replying to my message. What I would like to do is remove the arrow lines from the plot, but keep the vector labels. Similar to the Factominer CA, with the vectors as triangles or points in the graph (or just the label names). The arrow lines just make the graph very busy with large datasets.

Thanks!
Em

**Comment by fawda123** [comment]
Ah I had forgotten that this is already possible, just do this:

``` r
ord <- prcomp(iris[, 1:4])
ggord(ord, iris$Species, arrow = NULL)
```

I did change the help file to make this more clear, see adc8d3e5ab2a8989652e57755fa82fe1835dfff4
