### ISSUE TITLE
point and font size in CA

### ISSUE THREAD

**Issue by emsa999** [fawda123/ggord#6]
Hi Marcus,

Is it possible to change the point and font size of the points and factor name labels in the CA graph of ggord?
Thank you,
Emily

**Comment by fawda123** [comment]
Hi Emily, like this?

``` r
library(ggord)
library(ade4)

ord <- dudi.coa(iris[, 1:4], scannf = FALSE, nf = 4)

ggord(ord, iris$Species, size = 7, txt = 7)
```

**Comment by emsa999** [comment]
Thank you so much Marcus! That is perfect!

On Fri, Nov 20, 2015 at 9:37 AM, Marcus W Beck notifications@github.com
wrote:

> Hi Emily, like this?
> 
> library(ggord)
> library(ade4)
> ord <- dudi.coa(iris[, 1:4], scannf = FALSE, nf = 4)
> 
> ggord(ord, iris$Species, size = 7, txt = 7)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fawda123/ggord/issues/6#issuecomment-158417750.

## 

Emily Choy
W. Garfield Weston Doctoral Fellow for Northern Research
International Arctic Science Committee Fellow
University of Manitoba
501 University Crescent
Winnipeg MB
R3T2N6
(204) 984-2425
https://sites.google.com/site/emilyschoy
