### ISSUE TITLE
ggord: allow filled ellipses using geom_polygon

### ISSUE THREAD

**Issue by friendly** [fawda123/ggord#8]
`ggord` is quite nice. One enhancement would be to allow ellipses to be filled rather than just outlined. The change is simple: just substitute `geom_polygon` for `geom_path`.

**Comment by fawda123** [comment]
@friendly Sorry, I just saw this!  Check it out a861ec84355918ac4f4917f5d5eeb96407075bb5
The new argument, `poly = T`, controls shaded or open ellipses.

**Comment by friendly** [comment]
Thanks for this.  They look great.
